# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS H2 (TEST)
# ==========================================

# Parâmetros de Conexão JDBC
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (Acesso via navegador em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Adia a inicialização de scripts SQL (como import.sql) para após a criação das tabelas pelo Hibernate
spring.jpa.defer-datasource-initialization=true
